function y=ComputePredictionScore(dataMatrix, ...
                                  weights, ...
                                  rangeMins, ...
                                  rangeMaxs, ...
                                  motifTrackInd)
if size(weights,1) ~= 1
  error 'weights needs to be a row vector, not a column vector';
end
rangeMaxs2 = rangeMaxs-rangeMins;
negInd = find(rangeMaxs2 <= 0);
if length(negInd) == 0
  y=(dataMatrix(:,motifTrackInd) >= rangeMins(motifTrackInd)) .* ...
    (bsxfun(@rdivide, ...
           bsxfun(@minus, ...
                  bsxfun(@max, ...
                         rangeMins, ...
                         bsxfun(@min, ...
                                rangeMaxs, ...
                                dataMatrix)), ...
                  rangeMins), ...
           rangeMaxs2) * weights');
else
  T = length(weights);
  posInd = setdiff(1:T, negInd);
  if length(posInd) > 0
    ypos = bsxfun(@rdivide, ...
                      bsxfun(@minus, ...
                             bsxfun(@max, ...
                                    rangeMins(posInd), ...
                                    bsxfun(@min, ...
                                           rangeMaxs(posInd), ...
                                           dataMatrix(:,posInd))), ...
                             rangeMins(posInd)), ...
                      rangeMaxs2(posInd)) * weights(posInd)';
  else
    ypos = 0;
  end
  yneg = bsxfun(@ge, dataMatrix(:,negInd), rangeMins(negInd)) * weights(negInd)';
  y = (dataMatrix(:,motifTrackInd) >= rangeMins(motifTrackInd)) .* (ypos + yneg);
end
